//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Triathlon
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSCRIPTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INSCRIPTION()
        {
            this.VERIFIERs = new HashSet<VERIFIER>();
        }
    
        public string numTriathlon { get; set; }
        public string numDossard { get; set; }
        public Nullable<System.DateTime> dateInscription { get; set; }
        public Nullable<decimal> tempsCourseCyscliste { get; set; }
        public Nullable<decimal> tempsCourse { get; set; }
        public Nullable<decimal> tempsNatation { get; set; }
        public string numeroTriathlete { get; set; }
    
        public virtual TRIATHLETE TRIATHLETE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VERIFIER> VERIFIERs { get; set; }
        public virtual TRIATHLON TRIATHLON { get; set; }
    }
}
