//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Triathlon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TriathlonEntities : DbContext
    {
        public TriathlonEntities()
            : base("name=TriathlonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AGE> AGEs { get; set; }
        public virtual DbSet<INSCRIPTION> INSCRIPTIONs { get; set; }
        public virtual DbSet<PRODUIT> PRODUITs { get; set; }
        public virtual DbSet<TRIATHLETE> TRIATHLETEs { get; set; }
        public virtual DbSet<TYPE_TRIATHLON> TYPE_TRIATHLON { get; set; }
        public virtual DbSet<VERIFIER> VERIFIERs { get; set; }
        public virtual DbSet<TRIATHLON> TRIATHLONs { get; set; }
    
        public virtual ObjectResult<GetClassement_Result> GetClassement(string codeTri)
        {
            var codeTriParameter = codeTri != null ?
                new ObjectParameter("CodeTri", codeTri) :
                new ObjectParameter("CodeTri", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetClassement_Result>("GetClassement", codeTriParameter);
        }
    }
}
