//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Triathlon
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRIATHLETE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRIATHLETE()
        {
            this.INSCRIPTIONs = new HashSet<INSCRIPTION>();
        }
    
        public string numeroTriathlete { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public System.DateTime dateNaissance { get; set; }
        public string pays { get; set; }
        public string ville { get; set; }
        public string numLicence { get; set; }
        public Nullable<System.DateTime> dateObtention { get; set; }
        public string codePostal { get; set; }
        public string codeAge { get; set; }
    
        public virtual AGE AGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSCRIPTION> INSCRIPTIONs { get; set; }
    }
}
