//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Triathlon
{
    using System;
    using System.Collections.Generic;
    
    public partial class VERIFIER
    {
        public string codeProduit { get; set; }
        public string numTriathlon { get; set; }
        public string numDossard { get; set; }
        public string prelevement { get; set; }
    
        public virtual INSCRIPTION INSCRIPTION { get; set; }
        public virtual PRODUIT PRODUIT { get; set; }
    }
}
